before_script:
  - psql -c 'create database bookyt_test' -U postgres
  - bundle exec rake bookyt:travis
  - bundle exec rake db:schema:load

env:
  - DB=postgresql

script: "bundle exec rake spec"

# whitelist
branches:
  only:
    - master
    - stable
    - staging
    - api

rvm:
  - 2.2.2

bundler_args: "--binstubs --without development"

# IRC notification
notifications:
  irc: "irc.freenode.org#cyt"
